project_id = "kivdqjyvahabsgqtszie"

[functions.send-order-notification]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.create-embedded-checkout]
verify_jwt = false

[functions.validate-delivery-address]
verify_jwt = false
